source("https://bioconductor.org/biocLite.R")
biocLite("DESeq2")
library("DESeq2")
setwd("~/RNASeq/ReadCounts")
cts <- as.matrix(read.csv("filtered_counts.csv", header = TRUE, row.names = 1))
condition <- c(rep("SPF", 9), rep("GF", 7))
col <- data.frame(condition)
rownames(col) <- colnames(cts)
cts <- cts[, rownames(col)]
dds <- DESeqDataSetFromMatrix(countData = cts, colData = col, design = ~ condition)
dds <- dds[ rowSums(counts(dds)) > 1, ]
dds$condition <- relevel(dds$condition, "GF")
dds <- DESeq(dds)
res <- results(dds)
resOrdered <- res[order(res$padj),]
resSig <- subset(resOrdered, padj < 0.05)
write.csv(as.data.frame(res), file = "DESeq2_DE_Results.csv")
write.csv(as.data.frame(resOrdered), file = "DESeq2_DE_Ordered_Results.csv")
write.csv(as.data.frame(resSig), file = "DESeq2_DE_Sig_Results.csv")
pdf("MA_plot.pdf")
plotMA(res)
dev.off()
pdf("MA_plot_resSig.pdf")
plotMA(resSig)
dev.off()
