source('http://bioconductor.org/biocLite.R')
library(edgeR)
x <- read.csv('filtered_counts.csv', row.names = 1)
group <- factor(c(rep('SPF',9), rep('GF',7)))
y <- DGEList(counts = x,group=group)
y <- calcNormFactors(y, method = 'TMM')
design <- model.matrix(~group)
y<-estimateDisp(y,design)
fit <-glmFit(y,design)
lrt <-glmLRT(fit,coef=2)
topTags(lrt, n=10, adjust.method = 'fdr', sort.by = 'PValue', p.value = 0.050000)
write.csv(topTags(lrt),file= 'top_edgeR_lrt.csv')
is.de <- decideTestsDGE(lrt)
summary(is.de)
plotMD(lrt,status = is.de,values = c(1,-1),col=c('red','blue'),legend = 'topright')
