source("https://bioconductor.org/biocLite.R")
biocLite("NOISeq")
library("NOISeq")
countdata <- as.matrix(read.csv("example_data.csv", header = TRUE, row.names = 1))
condition <- c(rep("treated", 3), rep("untreated", 4))
coldata <- data.frame(condition)
rownames(coldata) <- colnames(countdata)
countdata<- filtered.data(countdata, factor = coldata$condition, norm = FALSE, depth = NULL, method = 1, cv.cutoff = 100, cpm = 1, p.adj = "fdr")
mydata <- readData(data = countdata, factors = coldata)
results <- noiseq(mydata, factor = "condition", norm = "tmm", replicates = "no")
results.deg <- degenes(results, q = 0.8, M = NULL)
out <- results@results[[1]]
write.csv(out, file = "NOISeq_DE_Results.csv", quote = FALSE)
write.csv(results.deg, file = "NOISeq_DE_Sig_Results.csv", quote = FALSE)
pdf("EXP_plot.pdf")
DE.plot(results, q=0.9, graphic="expr", log.scale = TRUE)
dev.off()
pdf("MD_plot.pdf")
DE.plot(results, q=0.8, graphic="MD")
dev.off()
